import type { Tenant } from '../types';

export const initialTenants: Tenant[] = [
  {
    id: 't-1',
    businessName: 'The Magic Bottle - Shakes & Cafe',
    legalName: 'Magic Bottle Hospitality LLP',
    restaurantType: 'Cafe',
    ownerName: 'Ajay Yadav',
    ownerEmail: 'ajay@magicbottle.com',
    ownerPhone: '+91 98765 43210',
    gstin: '27AABCM1234F1Z5',
    city: 'Mumbai',
    state: 'Maharashtra',
    plan: 'Professional',
    status: 'Active',
    maxOutlets: 3,
    outlets: [
      { id: 'o-1', name: 'Bandra Flagship', code: 'MB-BND', city: 'Mumbai', isActive: true, tableCount: 16 },
      { id: 'o-2', name: 'Powai Central', code: 'MB-POW', city: 'Mumbai', isActive: true, tableCount: 12 },
    ],
    joinedAt: '2026-03-15',
    subscriptionExpiresAt: '2027-03-15',
    features: {
      enableKds: true,
      enableWaiterApp: true,
      enableAggregators: true,
      enableRecipeInventory: true,
      enableKhataBook: false,
    },
  },
  {
    id: 't-2',
    businessName: 'Spice Garden Multi-Cuisine',
    legalName: 'Spice Garden Foods Pvt Ltd',
    restaurantType: 'FineDine',
    ownerName: 'Vikram Malhotra',
    ownerEmail: 'vikram@spicegarden.com',
    ownerPhone: '+91 91234 56789',
    gstin: '29ABCDE1234FZ5',
    city: 'Bengaluru',
    state: 'Karnataka',
    plan: 'Enterprise',
    status: 'Active',
    maxOutlets: 5,
    outlets: [
      { id: 'o-3', name: 'Indiranagar Prime', code: 'SG-IND', city: 'Bengaluru', isActive: true, tableCount: 28 },
      { id: 'o-4', name: 'Koramangala 5th Block', code: 'SG-KOR', city: 'Bengaluru', isActive: true, tableCount: 24 },
      { id: 'o-5', name: 'Whitefield ITPL', code: 'SG-WHF', city: 'Bengaluru', isActive: true, tableCount: 32 },
    ],
    joinedAt: '2026-01-10',
    subscriptionExpiresAt: '2027-01-10',
    features: {
      enableKds: true,
      enableWaiterApp: true,
      enableAggregators: true,
      enableRecipeInventory: true,
      enableKhataBook: true,
    },
  },
  {
    id: 't-3',
    businessName: 'Urban Chai & Bakery Express',
    legalName: 'Urban Foodworks LLP',
    restaurantType: 'QSR',
    ownerName: 'Pooja Hegde',
    ownerEmail: 'pooja@urbanchai.in',
    ownerPhone: '+91 99887 76655',
    city: 'Pune',
    state: 'Maharashtra',
    plan: 'Starter',
    status: 'Active',
    maxOutlets: 1,
    outlets: [
      { id: 'o-6', name: 'FC Road Express', code: 'UC-FCR', city: 'Pune', isActive: true, tableCount: 6 },
    ],
    joinedAt: '2026-05-02',
    subscriptionExpiresAt: '2027-05-02',
    features: {
      enableKds: false,
      enableWaiterApp: false,
      enableAggregators: true,
      enableRecipeInventory: false,
      enableKhataBook: false,
    },
  },
  {
    id: 't-4',
    businessName: 'The Royal Biryani House',
    legalName: 'Royal Dawat Cuisines',
    restaurantType: 'Restaurant' as any,
    ownerName: 'Mohammad Farooq',
    ownerEmail: 'farooq@royalbiryani.com',
    ownerPhone: '+91 98200 11223',
    city: 'Hyderabad',
    state: 'Telangana',
    plan: 'Professional',
    status: 'Trial',
    maxOutlets: 2,
    outlets: [
      { id: 'o-7', name: 'Charminar Main', code: 'RBH-CHR', city: 'Hyderabad', isActive: true, tableCount: 20 },
    ],
    joinedAt: '2026-08-20',
    subscriptionExpiresAt: '2026-09-04',
    features: {
      enableKds: true,
      enableWaiterApp: true,
      enableAggregators: false,
      enableRecipeInventory: true,
      enableKhataBook: false,
    },
  },
  {
    id: 't-5',
    businessName: 'Cheesy Crust Pizzeria',
    legalName: 'Crust Bakers India',
    restaurantType: 'QSR',
    ownerName: 'Naveen Kumar',
    ownerEmail: 'naveen@cheesycrust.com',
    ownerPhone: '+91 97111 22334',
    city: 'Delhi NCR',
    state: 'Delhi',
    plan: 'Starter',
    status: 'Suspended',
    maxOutlets: 1,
    outlets: [
      { id: 'o-8', name: 'Sector 18 Outlet', code: 'CCP-SEC', city: 'Noida', isActive: false, tableCount: 8 },
    ],
    joinedAt: '2026-02-11',
    subscriptionExpiresAt: '2026-08-11',
    features: {
      enableKds: false,
      enableWaiterApp: false,
      enableAggregators: true,
      enableRecipeInventory: false,
      enableKhataBook: false,
    },
  },
  {
    id: 't-6',
    businessName: 'Green Leaf Vegan Bistro',
    legalName: 'Earth Foods Private Ltd',
    restaurantType: 'Cafe',
    ownerName: 'Ananya Sharma',
    ownerEmail: 'ananya@greenleaf.org',
    ownerPhone: '+91 98450 99887',
    city: 'Bengaluru',
    state: 'Karnataka',
    plan: 'Professional',
    status: 'Active',
    maxOutlets: 2,
    outlets: [
      { id: 'o-9', name: 'Koramangala 3rd Block', code: 'GL-KOR', city: 'Bengaluru', isActive: true, tableCount: 14 },
    ],
    joinedAt: '2026-06-18',
    subscriptionExpiresAt: '2027-06-18',
    features: {
      enableKds: true,
      enableWaiterApp: true,
      enableAggregators: true,
      enableRecipeInventory: true,
      enableKhataBook: true,
    },
  },
  {
    id: 't-7',
    businessName: 'Smoky Bar & Kitchen',
    legalName: 'Smoky Hospitality Group',
    restaurantType: 'BarAndRestro',
    ownerName: 'Rohan Deshmukh',
    ownerEmail: 'rohan@smokybar.com',
    ownerPhone: '+91 99100 44332',
    city: 'Goa',
    state: 'Goa',
    plan: 'Enterprise',
    status: 'Active',
    maxOutlets: 3,
    outlets: [
      { id: 'o-10', name: 'Candolim Beachside', code: 'SB-CND', city: 'Goa', isActive: true, tableCount: 30 },
      { id: 'o-11', name: 'Panjim Waterfront', code: 'SB-PAN', city: 'Goa', isActive: true, tableCount: 26 },
    ],
    joinedAt: '2026-04-01',
    subscriptionExpiresAt: '2027-04-01',
    features: {
      enableKds: true,
      enableWaiterApp: true,
      enableAggregators: false,
      enableRecipeInventory: true,
      enableKhataBook: true,
    },
  },
];
