<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>Major</RollForward>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0d50504a-d379-4db1-94df-e03c6561565a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.30" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PetBharke.Application\PetBharke.Application.csproj" />
    <ProjectReference Include="..\PetBharke.Infrastructure\PetBharke.Infrastructure.csproj" />
    <ProjectReference Include="..\PetBharke.Domain\PetBharke.Domain.csproj" />
  </ItemGroup>

</Project>
